FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["src/Presentation/ImpactSocial.WebAPI/ImpactSocial.WebAPI.csproj", "src/Presentation/ImpactSocial.WebAPI/"]
COPY ["src/Core/ImpactSocial.Application/ImpactSocial.Application.csproj", "src/Core/ImpactSocial.Application/"]
COPY ["src/Core/ImpactSocial.Domain/ImpactSocial.Domain.csproj", "src/Core/ImpactSocial.Domain/"]
COPY ["src/Infrastructure/ImpactSocial.Infrastructure/ImpactSocial.Infrastructure.csproj", "src/Infrastructure/ImpactSocial.Infrastructure/"]
COPY ["src/Infrastructure/ImpactSocial.Persistence/ImpactSocial.Persistence.csproj", "src/Infrastructure/ImpactSocial.Persistence/"]
RUN dotnet restore "src/Presentation/ImpactSocial.WebAPI/ImpactSocial.WebAPI.csproj"
COPY . .
WORKDIR "/src/src/Presentation/ImpactSocial.WebAPI"
RUN dotnet build "ImpactSocial.WebAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ImpactSocial.WebAPI.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ImpactSocial.WebAPI.dll"]
